--- Makefile.org	2022-07-21 15:55:10.508499755 +0900
+++ Makefile	2022-07-21 15:09:44.090348331 +0900
@@ -25,8 +25,10 @@
 
 .include "../../devel/libpeas/buildlink3.mk"
 .include "../../devel/glib2/schemas.mk"
+.include "../../devel/wayland/buildlink3.mk"
 .include "../../lang/python/application.mk"
 .include "../../x11/mate-desktop/buildlink3.mk"
 .include "../../x11/gtksourceview3/buildlink3.mk"
+.include "../../x11/libxkbcommon/buildlink3.mk"
 .include "../../sysutils/desktop-file-utils/desktopdb.mk"
 .include "../../mk/bsd.pkg.mk"
