view.csv:
	./togetterview.rb 1 >  view.csv
	./togetterview.rb 2 >> view.csv
	./togetterview.rb 3 >> view.csv
	./togetterview.rb 4 >> view.csv
	./togetterview.rb 5 >> view.csv
	./togetterview.rb 6 >> view.csv
	./togetterview.rb 7 >> view.csv
	./togetterview.rb 8 >> view.csv
	./togetterview.rb 9 >> view.csv
copy:
	cp view.csv ..
