(define baidu-olime-jp-show-segment-separator? #f)
(define baidu-olime-jp-segment-separator "|")
(define baidu-olime-jp-use-candidate-window? #t)
(define baidu-olime-jp-candidate-op-count 1)
(define baidu-olime-jp-nr-candidate-max 10)
(define baidu-olime-jp-select-candidate-by-numeral-key? #f)
(define baidu-olime-jp-widgets '(widget_baidu-olime-jp_input_mode widget_baidu-olime-jp_kana_input_method))
(define default-widget_baidu-olime-jp_input_mode 'action_baidu-olime-jp_direct)
(define baidu-olime-jp-input-mode-actions '(action_baidu-olime-jp_direct action_baidu-olime-jp_hiragana action_baidu-olime-jp_katakana action_baidu-olime-jp_halfkana action_baidu-olime-jp_halfwidth_alnum action_baidu-olime-jp_fullwidth_alnum))
(define default-widget_baidu-olime-jp_kana_input_method 'action_baidu-olime-jp_roma)
(define baidu-olime-jp-kana-input-method-actions '(action_baidu-olime-jp_roma action_baidu-olime-jp_kana action_baidu-olime-jp_azik action_baidu-olime-jp_act action_baidu-olime-jp_kzik))
