(define skk-begin-conv-with-completion-key '("<Alt> "))
(define skk-begin-conv-with-completion-key? (make-key-predicate '("<Alt> ")))
(define skk-commit-with-conv-completion-key '("<IgnoreCase><Control><Alt>j"))
(define skk-commit-with-conv-completion-key? (make-key-predicate '("<IgnoreCase><Control><Alt>j")))
(define skk-next-candidate-key '(generic-next-candidate-key))
(define skk-next-candidate-key? (make-key-predicate '(generic-next-candidate-key?)))
(define skk-prev-candidate-key '("<IgnoreCase>x" generic-prev-candidate-key))
(define skk-prev-candidate-key? (make-key-predicate '("<IgnoreCase>x" generic-prev-candidate-key?)))
(define skk-next-page-key '(generic-next-page-key))
(define skk-next-page-key? (make-key-predicate '(generic-next-page-key?)))
(define skk-prev-page-key '(generic-prev-page-key))
(define skk-prev-page-key? (make-key-predicate '(generic-prev-page-key?)))
(define skk-backspace-key '(generic-backspace-key))
(define skk-backspace-key? (make-key-predicate '(generic-backspace-key?)))
(define skk-go-left-key '(generic-go-left-key))
(define skk-go-left-key? (make-key-predicate '(generic-go-left-key?)))
(define skk-go-right-key '(generic-go-right-key))
(define skk-go-right-key? (make-key-predicate '(generic-go-right-key?)))
