(define google-cgiapi-jp-on-key '("<Control>\\" generic-on-key))
(define google-cgiapi-jp-on-key? (make-key-predicate '("<Control>\\" generic-on-key?)))
(define google-cgiapi-jp-off-key '("<Control>\\" generic-off-key))
(define google-cgiapi-jp-off-key? (make-key-predicate '("<Control>\\" generic-off-key?)))
(define google-cgiapi-jp-begin-conv-key '(generic-begin-conv-key))
(define google-cgiapi-jp-begin-conv-key? (make-key-predicate '(generic-begin-conv-key?)))
(define google-cgiapi-jp-commit-key '(generic-commit-key))
(define google-cgiapi-jp-commit-key? (make-key-predicate '(generic-commit-key?)))
(define google-cgiapi-jp-cancel-key '(generic-cancel-key))
(define google-cgiapi-jp-cancel-key? (make-key-predicate '(generic-cancel-key?)))
(define google-cgiapi-jp-next-candidate-key '(generic-next-candidate-key))
(define google-cgiapi-jp-next-candidate-key? (make-key-predicate '(generic-next-candidate-key?)))
(define google-cgiapi-jp-prev-candidate-key '(generic-prev-candidate-key))
(define google-cgiapi-jp-prev-candidate-key? (make-key-predicate '(generic-prev-candidate-key?)))
(define google-cgiapi-jp-next-page-key '(generic-next-page-key))
(define google-cgiapi-jp-next-page-key? (make-key-predicate '(generic-next-page-key?)))
(define google-cgiapi-jp-prev-page-key '(generic-prev-page-key))
(define google-cgiapi-jp-prev-page-key? (make-key-predicate '(generic-prev-page-key?)))
