(define yahoo-jp-beginning-of-preedit-key '(generic-beginning-of-preedit-key))
(define yahoo-jp-beginning-of-preedit-key? (make-key-predicate '(generic-beginning-of-preedit-key?)))
(define yahoo-jp-end-of-preedit-key '(generic-end-of-preedit-key))
(define yahoo-jp-end-of-preedit-key? (make-key-predicate '(generic-end-of-preedit-key?)))
(define yahoo-jp-kill-key '(generic-kill-key))
(define yahoo-jp-kill-key? (make-key-predicate '(generic-kill-key?)))
(define yahoo-jp-kill-backward-key '(generic-kill-backward-key))
(define yahoo-jp-kill-backward-key? (make-key-predicate '(generic-kill-backward-key?)))
(define yahoo-jp-backspace-key '(generic-backspace-key))
(define yahoo-jp-backspace-key? (make-key-predicate '(generic-backspace-key?)))
(define yahoo-jp-delete-key '(generic-delete-key))
(define yahoo-jp-delete-key? (make-key-predicate '(generic-delete-key?)))
(define yahoo-jp-go-left-key '(generic-go-left-key))
(define yahoo-jp-go-left-key? (make-key-predicate '(generic-go-left-key?)))
(define yahoo-jp-go-right-key '(generic-go-right-key))
(define yahoo-jp-go-right-key? (make-key-predicate '(generic-go-right-key?)))
(define yahoo-jp-vi-escape-key '("escape" "<Control>["))
(define yahoo-jp-vi-escape-key? (make-key-predicate '("escape" "<Control>[")))
