(define anthy-show-segment-separator? #f)
(define anthy-segment-separator "|")
(define anthy-use-candidate-window? #t)
(define anthy-candidate-op-count 1)
(define anthy-nr-candidate-max 10)
(define anthy-select-candidate-by-numeral-key? #f)
(define anthy-widgets '(widget_anthy_input_mode widget_anthy_kana_input_method))
(define default-widget_anthy_input_mode 'action_anthy_direct)
(define anthy-input-mode-actions '(action_anthy_direct action_anthy_hiragana action_anthy_katakana action_anthy_halfkana action_anthy_halfwidth_alnum action_anthy_fullwidth_alnum))
(define default-widget_anthy_kana_input_method 'action_anthy_roma)
(define anthy-kana-input-method-actions '(action_anthy_roma action_anthy_kana action_anthy_azik action_anthy_act action_anthy_kzik))
