(define anthy-beginning-of-preedit-key '(generic-beginning-of-preedit-key))
(define anthy-beginning-of-preedit-key? (make-key-predicate '(generic-beginning-of-preedit-key?)))
(define anthy-end-of-preedit-key '(generic-end-of-preedit-key))
(define anthy-end-of-preedit-key? (make-key-predicate '(generic-end-of-preedit-key?)))
(define anthy-kill-key '(generic-kill-key))
(define anthy-kill-key? (make-key-predicate '(generic-kill-key?)))
(define anthy-kill-backward-key '(generic-kill-backward-key))
(define anthy-kill-backward-key? (make-key-predicate '(generic-kill-backward-key?)))
(define anthy-backspace-key '(generic-backspace-key))
(define anthy-backspace-key? (make-key-predicate '(generic-backspace-key?)))
(define anthy-delete-key '(generic-delete-key))
(define anthy-delete-key? (make-key-predicate '(generic-delete-key?)))
(define anthy-go-left-key '(generic-go-left-key))
(define anthy-go-left-key? (make-key-predicate '(generic-go-left-key?)))
(define anthy-go-right-key '(generic-go-right-key))
(define anthy-go-right-key? (make-key-predicate '(generic-go-right-key?)))
(define anthy-vi-escape-key '("escape" "<Control>["))
(define anthy-vi-escape-key? (make-key-predicate '("escape" "<Control>[")))
