(define prime-register-key '("<Control>w"))
(define prime-register-key? (make-key-predicate '("<Control>w")))
(define prime-typing-mode-hiragana-key '("F6"))
(define prime-typing-mode-hiragana-key? (make-key-predicate '("F6")))
(define prime-typing-mode-katakana-key '("F7"))
(define prime-typing-mode-katakana-key? (make-key-predicate '("F7")))
(define prime-typing-mode-hankana-key '("F8"))
(define prime-typing-mode-hankana-key? (make-key-predicate '("F8")))
(define prime-typing-mode-wideascii-key '("F9"))
(define prime-typing-mode-wideascii-key? (make-key-predicate '("F9")))
(define prime-typing-mode-ascii-key '("F10"))
(define prime-typing-mode-ascii-key? (make-key-predicate '("F10")))
