(define ajax-ime-on-key '("<Control>\\" generic-on-key))
(define ajax-ime-on-key? (make-key-predicate '("<Control>\\" generic-on-key?)))
(define ajax-ime-off-key '("<Control>\\" generic-off-key))
(define ajax-ime-off-key? (make-key-predicate '("<Control>\\" generic-off-key?)))
(define ajax-ime-begin-conv-key '(generic-begin-conv-key))
(define ajax-ime-begin-conv-key? (make-key-predicate '(generic-begin-conv-key?)))
(define ajax-ime-commit-key '(generic-commit-key))
(define ajax-ime-commit-key? (make-key-predicate '(generic-commit-key?)))
(define ajax-ime-cancel-key '(generic-cancel-key))
(define ajax-ime-cancel-key? (make-key-predicate '(generic-cancel-key?)))
(define ajax-ime-next-candidate-key '(generic-next-candidate-key))
(define ajax-ime-next-candidate-key? (make-key-predicate '(generic-next-candidate-key?)))
(define ajax-ime-prev-candidate-key '(generic-prev-candidate-key))
(define ajax-ime-prev-candidate-key? (make-key-predicate '(generic-prev-candidate-key?)))
(define ajax-ime-next-page-key '(generic-next-page-key))
(define ajax-ime-next-page-key? (make-key-predicate '(generic-next-page-key?)))
(define ajax-ime-prev-page-key '(generic-prev-page-key))
(define ajax-ime-prev-page-key? (make-key-predicate '(generic-prev-page-key?)))
