(define google-cgiapi-jp-hiragana-key '("<Shift>F6"))
(define google-cgiapi-jp-hiragana-key? (make-key-predicate '("<Shift>F6")))
(define google-cgiapi-jp-katakana-key '("<Shift>F7"))
(define google-cgiapi-jp-katakana-key? (make-key-predicate '("<Shift>F7")))
(define google-cgiapi-jp-halfkana-key '("<Shift>F8"))
(define google-cgiapi-jp-halfkana-key? (make-key-predicate '("<Shift>F8")))
(define google-cgiapi-jp-halfwidth-alnum-key '("<Shift>F10"))
(define google-cgiapi-jp-halfwidth-alnum-key? (make-key-predicate '("<Shift>F10")))
(define google-cgiapi-jp-fullwidth-alnum-key '("<Shift>F9"))
(define google-cgiapi-jp-fullwidth-alnum-key? (make-key-predicate '("<Shift>F9")))
(define google-cgiapi-jp-kana-toggle-key '())
(define google-cgiapi-jp-kana-toggle-key? (make-key-predicate '()))
(define google-cgiapi-jp-alkana-toggle-key '())
(define google-cgiapi-jp-alkana-toggle-key? (make-key-predicate '()))
(define google-cgiapi-jp-next-prediction-key '("tab" "down" "<IgnoreCase><Control>n" "<IgnoreCase><Control>i"))
(define google-cgiapi-jp-next-prediction-key? (make-key-predicate '("tab" "down" "<IgnoreCase><Control>n" "<IgnoreCase><Control>i")))
(define google-cgiapi-jp-prev-prediction-key '(generic-prev-candidate-key))
(define google-cgiapi-jp-prev-prediction-key? (make-key-predicate '(generic-prev-candidate-key?)))
