(define anthy-on-key '(generic-on-key))
(define anthy-on-key? (make-key-predicate '(generic-on-key?)))
(define anthy-off-key '(generic-off-key))
(define anthy-off-key? (make-key-predicate '(generic-off-key?)))
(define anthy-begin-conv-key '(generic-begin-conv-key))
(define anthy-begin-conv-key? (make-key-predicate '(generic-begin-conv-key?)))
(define anthy-commit-key '(generic-commit-key))
(define anthy-commit-key? (make-key-predicate '(generic-commit-key?)))
(define anthy-cancel-key '(generic-cancel-key))
(define anthy-cancel-key? (make-key-predicate '(generic-cancel-key?)))
(define anthy-next-candidate-key '(generic-next-candidate-key))
(define anthy-next-candidate-key? (make-key-predicate '(generic-next-candidate-key?)))
(define anthy-prev-candidate-key '(generic-prev-candidate-key))
(define anthy-prev-candidate-key? (make-key-predicate '(generic-prev-candidate-key?)))
(define anthy-next-page-key '(generic-next-page-key))
(define anthy-next-page-key? (make-key-predicate '(generic-next-page-key?)))
(define anthy-prev-page-key '(generic-prev-page-key))
(define anthy-prev-page-key? (make-key-predicate '(generic-prev-page-key?)))
