(define prime-custom-default-language 'Japanese)
(define prime-language-toggle-key '("F11"))
(define prime-language-toggle-key? (make-key-predicate '("F11")))
(define prime-auto-register-mode? #t)
(define prime-custom-japanese-space 'wide)
(define prime-altspace-key '("<Control> " "<Alt> "))
(define prime-altspace-key? (make-key-predicate '("<Control> " "<Alt> ")))
(define prime-server-setting? 'unixdomain)
(define prime-command-path "prime")
(define prime-tcpserver-name "localhost")
(define prime-tcpserver-port 1180)
