(define social-ime-beginning-of-preedit-key '(generic-beginning-of-preedit-key))
(define social-ime-beginning-of-preedit-key? (make-key-predicate '(generic-beginning-of-preedit-key?)))
(define social-ime-end-of-preedit-key '(generic-end-of-preedit-key))
(define social-ime-end-of-preedit-key? (make-key-predicate '(generic-end-of-preedit-key?)))
(define social-ime-kill-key '(generic-kill-key))
(define social-ime-kill-key? (make-key-predicate '(generic-kill-key?)))
(define social-ime-kill-backward-key '(generic-kill-backward-key))
(define social-ime-kill-backward-key? (make-key-predicate '(generic-kill-backward-key?)))
(define social-ime-backspace-key '(generic-backspace-key))
(define social-ime-backspace-key? (make-key-predicate '(generic-backspace-key?)))
(define social-ime-delete-key '(generic-delete-key))
(define social-ime-delete-key? (make-key-predicate '(generic-delete-key?)))
(define social-ime-go-left-key '(generic-go-left-key))
(define social-ime-go-left-key? (make-key-predicate '(generic-go-left-key?)))
(define social-ime-go-right-key '(generic-go-right-key))
(define social-ime-go-right-key? (make-key-predicate '(generic-go-right-key?)))
(define social-ime-vi-escape-key '("escape" "<Control>["))
(define social-ime-vi-escape-key? (make-key-predicate '("escape" "<Control>[")))
