(define yahoo-jp-show-segment-separator? #f)
(define yahoo-jp-segment-separator "|")
(define yahoo-jp-use-candidate-window? #t)
(define yahoo-jp-candidate-op-count 1)
(define yahoo-jp-nr-candidate-max 10)
(define yahoo-jp-select-candidate-by-numeral-key? #f)
(define yahoo-jp-widgets '(widget_yahoo-jp_input_mode widget_yahoo-jp_kana_input_method))
(define default-widget_yahoo-jp_input_mode 'action_yahoo-jp_direct)
(define yahoo-jp-input-mode-actions '(action_yahoo-jp_direct action_yahoo-jp_hiragana action_yahoo-jp_katakana action_yahoo-jp_halfkana action_yahoo-jp_halfwidth_alnum action_yahoo-jp_fullwidth_alnum))
(define default-widget_yahoo-jp_kana_input_method 'action_yahoo-jp_roma)
(define yahoo-jp-kana-input-method-actions '(action_yahoo-jp_roma action_yahoo-jp_kana action_yahoo-jp_azik action_yahoo-jp_act action_yahoo-jp_kzik))
