(define byeoru-next-candidate-key '(generic-next-candidate-key))
(define byeoru-next-candidate-key? (make-key-predicate '(generic-next-candidate-key?)))
(define byeoru-prev-candidate-key '(generic-prev-candidate-key))
(define byeoru-prev-candidate-key? (make-key-predicate '(generic-prev-candidate-key?)))
(define byeoru-next-page-key '(generic-next-page-key))
(define byeoru-next-page-key? (make-key-predicate '(generic-next-page-key?)))
(define byeoru-prev-page-key '(generic-prev-page-key))
(define byeoru-prev-page-key? (make-key-predicate '(generic-prev-page-key?)))
(define byeoru-backspace-key '(generic-backspace-key))
(define byeoru-backspace-key? (make-key-predicate '(generic-backspace-key?)))
(define byeoru-delete-key '(generic-delete-key))
(define byeoru-delete-key? (make-key-predicate '(generic-delete-key?)))
(define byeoru-go-left-key '(generic-go-left-key))
(define byeoru-go-left-key? (make-key-predicate '(generic-go-left-key?)))
(define byeoru-go-right-key '(generic-go-right-key))
(define byeoru-go-right-key? (make-key-predicate '(generic-go-right-key?)))
(define byeoru-beginning-of-preedit-key '(generic-beginning-of-preedit-key))
(define byeoru-beginning-of-preedit-key? (make-key-predicate '(generic-beginning-of-preedit-key?)))
(define byeoru-end-of-preedit-key '(generic-end-of-preedit-key))
(define byeoru-end-of-preedit-key? (make-key-predicate '(generic-end-of-preedit-key?)))
