(define elatin-rules 'elatin-rules-latin-prefix)
(define elatin-esc-turns-off? #f)
(define elatin-nr-candidates-max 10)
(define elatin-numeral-key-selects-candidate? #t)
(define elatin-use-completion? #f)
(define elatin-show-all-if-ambiguous? #f)
(define elatin-on-key '("<Control>\\"))
(define elatin-on-key? (make-key-predicate '("<Control>\\")))
(define elatin-off-key '("<Control>\\"))
(define elatin-off-key? (make-key-predicate '("<Control>\\")))
(define elatin-backspace-key '(generic-backspace-key))
(define elatin-backspace-key? (make-key-predicate '(generic-backspace-key?)))
(define elatin-commit-key '(generic-commit-key))
(define elatin-commit-key? (make-key-predicate '(generic-commit-key?)))
(define elatin-cancel-key '(generic-cancel-key))
(define elatin-cancel-key? (make-key-predicate '(generic-cancel-key?)))
(define elatin-next-candidate-key '("down" "<IgnoreCase><Control>n"))
(define elatin-next-candidate-key? (make-key-predicate '("down" "<IgnoreCase><Control>n")))
(define elatin-prev-candidate-key '("up" "<IgnoreCase><Control>p"))
(define elatin-prev-candidate-key? (make-key-predicate '("up" "<IgnoreCase><Control>p")))
(define elatin-next-page-key '(generic-next-page-key))
(define elatin-next-page-key? (make-key-predicate '(generic-next-page-key?)))
(define elatin-prev-page-key '(generic-prev-page-key))
(define elatin-prev-page-key? (make-key-predicate '(generic-prev-page-key?)))
(define elatin-completion-key '("tab"))
(define elatin-completion-key? (make-key-predicate '("tab")))
