name: NetBSD CI

on:
  push:
  pull_request:

jobs:
  build-netbsd:
    runs-on: ubuntu-latest
    
      strategy:
      fail-fast: false
      matrix:
        machine: [alpha, evbarm-aarch64, evbarm-earmv7hf, i386, macppc, sparc, sparc64, vax]

    steps:
      - name: Build project in NetBSD/${{ matrix.machine }} environment
        uses: tsutsui/netbsd-cross-live-ci@master
        with:
          machine: "${{ matrix.machine }}"
          release: "10.1"

          prepare: |
            pkg_add perl

          configure: |
            sh configure

          build: |
            make
            make install
