#! /usr/bin/ruby -Ku

class EventView
	def initialize(line)
		@event = line
		@event = @event.gsub("    ### ","")
		@event = @event.gsub("\\","")
 		@event = @event.slice(0,@event.index("title=")-2)
	end
	def searchview(line)
		if @view 
			return
		end
		a = line.split(/ /)
		s=""
		s=a[5]
		s=s.slice(0,s.index("</span>"))
		s[0,s.index("span>")+5] = ""
		@view = s
	end
	def csv
		if @view == nil
			exit 
		end
		if @view == "new"
			exit 
		end
		@csv = @event + ',' + @view
		print " ",@csv,"\n"
	end
end

while line = STDIN.gets
	if line.include?("pagenation")
		break
	elsif line.include?("title=")
		a = EventView.new(line)
		line = STDIN.gets
		line = STDIN.gets
		line = STDIN.gets
		line = STDIN.gets
		line = STDIN.gets
		line = STDIN.gets
		if line.index("view")
			a.searchview(line)
			a.csv
		end
	elsif line.include?(' [](')
		if line.index("http")
			print line[line.index("http")..(line.rindex(")\n")-1)],","
		end
	end
end
