#! /usr/bin/ruby -Ku

class EventView
	def initialize(line)
		@event = line
		@event = @event.gsub("    ### ","")
		@event = @event.gsub("\\","")
		@event = @event.gsub("\n",",")
	end
	def searchview(line)
		if @view 
			return
		end
		a = line.split(/ /)
		@view = a[5]
	end
	def searchview2(line)
		if @view 
			return
		end
		a = line.split(/ /)
		@view = a[4]
	end
	def csv
		if @view == nil
			exit 
		end
		if @view == "new"
			exit 
		end
		@csv = @event + @view
		@csv = @csv.tr("\n","")
		@csv = @csv.tr("\\","")
		print " ",@csv," views\n"
	end
end

while line = STDIN.gets
	if line.include?("### ")
		a = EventView.new(line)
		line = STDIN.gets
		line = STDIN.gets
		line = STDIN.gets
		line = STDIN.gets
		a.searchview(line)
		a.csv
	end
end
