mod85:
	cp -p ./85/usr/X11R7/lib/modules/drivers/modesetting_drv.so /usr/X11R7/lib/modules/drivers/modesetting_drv.so.0

mod86:
	cp ./86/usr/X11R7/lib/modules/drivers/modesetting_drv.so

back:
	cp -p /usr/X11R7/lib/modules/drivers/modesetting_drv.so.0 /usr/X11R7/lib/modules/drivers/modesetting_drv.so.org
